index:
    path: /
    controller: App\Controller\DefaultController::index
    methods: GET
healthcheck:
    path: /healthcheck
    controller: App\Controller\SystemController::healthcheck
    methods: GET
