index:
    path: /
    controller: App\Controller\DefaultController::index
    methods: GET
healthcheck:
    path: /healthcheck
    controller: App\Controller\SystemController::healthcheck
    methods: GET
add_feedback:
    path: /feedback
    controller: App\Controller\FeedbackController::add
    methods: POST
list_feedback:
    path: /feedback
    controller: App\Controller\FeedbackController::list
    methods: GET
